version: "3.7"
services:
  redis:
    image: redis:6.0.9
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - tic-tac-toe-data:/var/lib/redis
  app:
    image: node:12-alpine
    command: sh -c "npm i --production && npm run prod"
    ports:
      - ${APP_PORT}:${APP_PORT}
    working_dir: /tic-tac-toe
    volumes:
      - ./:/tic-tac-toe
    environment:
      PORT: ${APP_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_CONNECTION: ${REDIS_CONNECTION}
      APP_KEY: ${APP_KEY}

volumes:
  tic-tac-toe-data:
